SPEAr clock.c fix Compilation error: spear*_clk_lookups not defined
While compiling linux for single board/machine compilation errors comes that
spear*_clk_lookups not defined for other machines. This happens because these
arrays are conditionally compiled.
This patch removes this error.

Signed-off-by: Viresh Kumar <viresh.kumar@st.com>