video/spear_camif: fix compilation error
spear_camif didn't include slab.h due to which it gives compilation
error. It happened when SPI was disabled as it indirectly included the
required header file.

drivers/media/video/spear_camif.c:1265:2: error: implicit declaration of function ‘kfree’
drivers/media/video/spear_camif.c: In function ‘camif_probe’:
drivers/media/video/spear_camif.c:1964:2: error: implicit declaration of function ‘kzalloc’

Signed-off-by: Shiraz Hashim <shiraz.hashim@st.com>
Reported-by: Vinit Shenoy <vinit.shenoy@st.com>
Reported-by: Vipul Kumar Samar <vipulkumar.samar@st.com>